In [1]:
# Sort, Search & Counting Functions

In [2]:
import numpy as np

In [3]:
arr = np.array([4,2,5,6,31,8,6,9,225,54])

In [4]:
arr

array([  4,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [5]:
np.sort(arr)

array([  2,   4,   5,   6,   6,   8,   9,  31,  54, 225])

In [6]:
np.searchsorted(arr, 34)

8

In [7]:
arr1 = np.array([0,345,445,0,0,0,0,56,78])

In [8]:
np.count_nonzero(arr1)

4

In [9]:
arr

array([  4,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [10]:
np.where(arr > 6)

(array([4, 5, 7, 8, 9]),)

In [11]:
np.extract(arr > 31, arr)

array([225,  54])

In [12]:
# Numpy Byte Swapping

In [13]:
arr.byteswap()

array([  288230376151711744,   144115188075855872,   360287970189639680,
         432345564227567616,  2233785415175766016,   576460752303423488,
         432345564227567616,   648518346341351424, -2233785415175766016,
        3891110078048108544])

In [14]:
# Numpy Copies & Views

In [15]:
arr

array([  4,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [16]:
a = np.copy(arr)

In [17]:
b = arr.view()

In [18]:
b

array([  4,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [19]:
arr

array([  4,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [20]:
b[0] = 32

In [21]:
b

array([ 32,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [22]:
arr

array([ 32,   2,   5,   6,  31,   8,   6,   9, 225,  54])

In [23]:
# Numpy Matrix Library

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
# Numpy - Linear Algebra

In [29]:
arr1 = np.random.randint([[2,3], [4,5]])

In [30]:
arr2 = np.random.randint([[2,3], [4,5]])

In [31]:
np.dot(arr1, arr2)

array([[ 0,  0],
       [ 8, 16]])

In [32]:
arr1@arr2

array([[ 0,  0],
       [ 8, 16]])